### ISSUE TITLE
Integration sometimes creates duplicate comments from messages.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-facebook#24]

**Comment by jollypirate268** [comment]
@corsacca take a look: https://gist.github.com/Shaked/9db67cea0ba5b7e9ade039c08c18780b

**Comment by corsacca** [comment]
@jollypirate268 i think the upgrade described in that link applies to requests made by facebook to any server. Usually in from their webhooks api. So when facebook sends a request, it expects a 200 back.
Instead of getting pushed information The D.T Facebook integration is the one doing the request and pulls facebook for the information. 
I think is issue has something to do with the cron job firing at the same time.

**Comment by corsacca** [comment]
Possibly fixed with https://github.com/DiscipleTools/disciple-tools-facebook/commit/38420f8d21a0c0a55be0b79f7cc7f241faf7bf26
Can't use Uptime Robot and WP-CRON

**Comment by jollypirate268** [comment]
Disabling Uptime Robot seems to be working (across a sample size of... about 7 updates !)

**Comment by corsacca** [comment]
We have not seen this issue since the fix.
