### ISSUE TITLE
FB reference number is being used and not the page name in places

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-facebook#27]
When a response is received from Facebook, the plugin assigns the source as Facebook but also adds the FB page reference number. It should use the name of the FB page (as stated in the FB admin plugin area) instead of the number.

![Screen Shot 2021-02-01 at 23 19 10 ](https://user-images.githubusercontent.com/43966676/106565876-1b235e80-64f5-11eb-9dba-d744f5753043.png)

**Comment by corsacca** [comment]
@mikeallbutt I can't reproduce this issue. If the page is in the facebook settings it will show the name, otherwise it will show the ID.
Also, the plugin does not add the "Facebook" Source.

**Comment by mikeallbutt** [comment]
The fix was found by restoring (and not having hidden) a item in the sources field (done in the Fields tab in WP Admin.).

**Comment by corsacca** [comment]
Thanks @mikeallbutt
