### ISSUE TITLE
Ability to set both the “Assigned to” and Sub-assigned to” for Facebook Messenger Contacts

### ISSUE THREAD

**Issue by jaichele70** [DiscipleTools/disciple-tools-facebook#29]
I’m working with a M2M team that has 2 DRs. Would it be possible to have all Facebook contacts sub-assigned to the DR that is not the default for the “Assigned To” under Status?

**Comment by corsacca** [comment]
Hey @jaichele70, this is now possible via the workflow builder. 
See https://disciple.tools/news/theme-release-v1-11-0/
