### ISSUE TITLE
Instructions correct on cron setup?

### ISSUE THREAD

**Issue by rdai** [DiscipleTools/disciple-tools-facebook#30]
Hi,

I am not sure if this is the right place to report this.

I followed the instructions on installation, under last section, 

4. Set up cron to get contacts every 5 minutes.
after I did "Check the "Disable wp-cron for Facebook" checkbox on the Facebook plugin settings page. And click update.", which I am pretty sure it was within 5 minutes of setting up uptimerobot, I got TONS of duplicates coming in. Now I am looking at over 1000 contacts where each is duplicated two or three times. Not sure if there is a bug in the code or just an timing issue that is amplified by the sequence in the instruction? Perhaps one needs to do "Check the "Disable wp-cron for Facebook" checkbox on the Facebook plugin settings page. And click update." before turn on the robot?

**Comment by rdai** [comment]
Just FYI I reset my DB and started over. I paused the uptimerobot, run the update, when all done then I turned uptimerobot back on. Don't know if that is what fixed it.

**Comment by corsacca** [comment]
Hey @rdai 
Sorry about all the duplicates.
I think you are right that "Disable wp-cron for Facebook" should be done first.
I'm updating the instructions to reflect it: https://github.com/DiscipleTools/disciple-tools-facebook/commit/8b76648bc681140f82179e29fd7bb67f98bdb159

Thanks for reporting this!
