### ISSUE TITLE
Facebook comment type being added twice.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-facebook#35]
![image](https://user-images.githubusercontent.com/24901539/194009655-8adaccf7-77c7-4478-be47-46c755453af3.png)

**Comment by micahmills** [comment]
This is because the default list is from the communications channel and then a comment type is added from the Facebook plugin.

**Comment by corsacca** [comment]
So the communication channel should be 'facebook' or the facebook plugin should have the type `contact_facebook`

**Comment by corsacca** [comment]
Or we change the facebook plugin label
